// ⚠️  AUTO-GENERATED by scripts/generate-products.mjs
// Do not edit this file manually.
// To add/edit products: edit files in public/products/<item-name>/

import type { Product } from '../types'

export const PRODUCTS: Product[] = [
  {
    "id": "beef-pot-pies-9",
    "name": "Beef Pot Pies (9 pcs)",
    "price": 65,
    "description": "Buttery flaky pastry packed with hearty beef and rich savoury gravy. A comforting homemade treat! 🥧",
    "category": "pastry",
    "images": [
      "/tokma-bakery/products/beef-pot-pies-9/beef-pot-pies.png"
    ]
  },
  {
    "id": "beef-pot-pies-16",
    "name": "Beef Pot Pies (16 pcs)",
    "price": 90,
    "description": "Buttery flaky pastry packed with hearty beef and rich savoury gravy. Perfect for large orders and events! 🥧",
    "category": "pastry",
    "images": [
      "/tokma-bakery/products/beef-pot-pies-16/beef-pot-pies.png"
    ]
  },
  {
    "id": "chicken-pot-pies-9",
    "name": "Chicken Pot Pies (9 pcs)",
    "price": 55,
    "description": "Flaky golden pastry filled with tender chicken and creamy savoury filling. Perfect for sharing! 🥧",
    "category": "pastry",
    "images": [
      "/tokma-bakery/products/chicken-pot-pies-9/chicken-pot-pies.png"
    ]
  },
  {
    "id": "chicken-pot-pies-16",
    "name": "Chicken Pot Pies (16 pcs)",
    "price": 80,
    "description": "Flaky golden pastry filled with tender chicken and creamy savoury filling. Great for events and gatherings! 🥧",
    "category": "pastry",
    "images": [
      "/tokma-bakery/products/chicken-pot-pies-16/chicken-pot-pies.png"
    ]
  },
  {
    "id": "fruit-tart-25",
    "name": "Fruit Tart (25 pcs)",
    "price": 45,
    "description": "Crisp buttery tart shells filled with silky custard cream and topped with fresh colourful fruits. 🍓",
    "category": "pastry",
    "images": [
      "/tokma-bakery/products/fruit-tart-25/fruit-tart.png"
    ]
  },
  {
    "id": "fruit-tart-36",
    "name": "Fruit Tart (36 pcs)",
    "price": 60,
    "description": "Crisp buttery tart shells filled with silky custard cream and topped with fresh colourful fruits. Great for kenduri! 🍓",
    "category": "pastry",
    "images": [
      "/tokma-bakery/products/fruit-tart-36/fruit-tart.png"
    ]
  },
  {
    "id": "fruit-tart-49",
    "name": "Fruit Tart (49 pcs)",
    "price": 80,
    "description": "Crisp buttery tart shells filled with silky custard cream and topped with fresh colourful fruits. Ideal for big celebrations! 🍓",
    "category": "pastry",
    "images": [
      "/tokma-bakery/products/fruit-tart-49/fruit-tart.png"
    ]
  }
]

export const CATEGORIES = ['All', 'cake', 'bread', 'pastry', 'cookies'] as const
export type CategoryFilter = typeof CATEGORIES[number]